# Chatwoot env — generated from deploy/templates/.env.chatwoot.tpl by install.sh
# Regenerate SECRET_KEY_BASE if leaked: openssl rand -hex 64

SECRET_KEY_BASE=${CHATWOOT_SECRET_KEY_BASE}

FRONTEND_URL=https://${DOMAIN}
DEFAULT_LOCALE=pt_BR
FORCE_SSL=true
ENABLE_ACCOUNT_SIGNUP=false
INSTALLATION_ENV=docker

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USERNAME=chatwoot
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DATABASE=chatwoot

REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}

MAILER_SENDER_EMAIL=Chatwoot <${EMAIL}>
SMTP_DOMAIN=${DOMAIN}
MAILER_INBOUND_EMAIL_DOMAIN=${DOMAIN}
RAILS_INBOUND_EMAIL_SERVICE=relay

ACTIVE_STORAGE_SERVICE=local

DISABLE_TELEMETRY=true
